version: "3.8"

services:
  api-service-provider:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    environment:
      - SERVER_PORT
      - LOG_LEVEL
      - GIT_COMMIT
      - APP_VERSION
    ports: 
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - service-network

  builder:
    image: node:14-alpine3.10
    volumes:
      - ".:/app"
    working_dir: /app


networks:
  service-network:
    name: service-network
