version: "3.8"

services:
  api-service-provider:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARG_GIT_COMMIT=${GIT_COMMIT}
        - ARG_APP_VERSION=${APP_VERSION}
    image: ${IMAGE_NAME}
    environment:
      - SERVER_PORT
      - LOG_LEVEL
    ports: 
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - service-network

  builder:
    image: node:14-alpine3.10
    volumes:
      - ".:/app"
    working_dir: /app


networks:
  service-network:
    name: service-network
