version: "3.3"

services:
  api-service-provider:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARG_GIT_COMMIT=${GIT_COMMIT}
        - ARG_APP_VERSION=${APP_VERSION}
    image: ${IMAGE_NAME}
    environment:
      - SERVER_PORT
      - LOG_LEVEL
    ports: 
      - "${SERVER_PORT}:${SERVER_PORT}"

  builder:
    image: node:14-alpine3.10
    volumes:
      - ".:/app"
    working_dir: /app

  infra:
    image: hashicorp/terraform:0.14.5
    environment:
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - AWS_ACCOUNT_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SESSION_TOKEN
      - TF_LOG
    volumes:
      - './infra/:/app'
    working_dir: /app
